// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.4.2
//   protoc               v5.28.2
// source: tarot_service.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Card, CardContent } from "./card.js";

export const protobufPackage = "byuljogak.tarot.reader";

export interface ReadTarotRequest {
}

export interface ReadTarotResponse {
  card: Card | undefined;
  cardContents: CardContent | undefined;
}

export const BYULJOGAK_TAROT_READER_PACKAGE_NAME = "byuljogak.tarot.reader";

export interface TarotServiceClient {
  readTarot(request: ReadTarotRequest): Observable<ReadTarotResponse>;
}

export interface TarotServiceController {
  readTarot(request: ReadTarotRequest): Promise<ReadTarotResponse> | Observable<ReadTarotResponse> | ReadTarotResponse;
}

export function TarotServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["readTarot"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("TarotService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("TarotService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const TAROT_SERVICE_NAME = "TarotService";
